import type {
  CustomWidget,
  DetectedField,
  ScanLimitation,
  ScanOptions,
  ScanResult,
} from '@quikfill/schemas'
import {
  detectAutocomplete,
  detectCustomSelect,
  getAriaLabel,
  getAriaLabelledByText,
  getCurrentValue,
  getInputType,
  getLabelText,
  getNearbyText,
  getOptions,
  getSectionHeading,
  getSelectorCandidates,
  getTriggerSelectorCandidates,
  getWidgetLabel,
  isCustomSelectTrigger,
  isFormControl,
  isVisible,
  type CustomSelectInfo,
  type FormControl,
} from './extract'
import { fingerprint, structureHash } from './fingerprint'

interface FrameContext {
  frame: string
  shadow: boolean
  /** The subtree we enumerate (Document, ShadowRoot, or a scoped Element). */
  walk: Document | ShadowRoot | Element
  /** Where id-based label/aria lookups resolve (may differ from `walk` when scoped). */
  lookup: Document | ShadowRoot
}

/** DOM ids generated by frameworks (React useId, MUI, emotion) — never meaningful. */
const GENERATED_ID_RE = /^(_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»|mui-\d+|css-[0-9a-z]+)$/i

/**
 * A field with no human-usable identity whose only "name" is a generated DOM id
 * (e.g. `_r_f4_`). These are noise — usually hidden inputs inside custom widgets.
 */
function isJunkField(f: DetectedField): boolean {
  const hasIdentity = f.labelText || f.name || f.ariaLabel || f.ariaLabelledByText || f.placeholder
  return !hasIdentity && !!f.domId && GENERATED_ID_RE.test(f.domId)
}

function lookupOf(root: Document | ShadowRoot | Element): Document | ShadowRoot {
  if (root.nodeType === 9 || root.nodeType === 11) return root as Document | ShadowRoot
  return (root as Element).getRootNode() as Document | ShadowRoot
}

/**
 * Scan a document or element (and its open shadow roots + same-origin iframes)
 * for fillable fields, including custom (non-native) dropdowns. Returns
 * DetectedField[] plus honest limitations. Pure DOM — no Chrome, no Vue.
 */
export function scanForms(
  root: Document | Element = document,
  options: ScanOptions = { includeHidden: false, scope: 'auto' },
): ScanResult {
  const fields: DetectedField[] = []
  const fieldEls: Element[] = []
  const limitations: ScanLimitation[] = []
  // Roots of detected custom widgets; their internal controls are suppressed.
  const suppressed: Element[] = []
  let counter = 0
  let frameCounter = 0

  const isSuppressed = (el: Element): boolean => suppressed.some((root) => root.contains(el))

  const push = (field: DetectedField, el: Element): void => {
    const visibleEnough = options.includeHidden || field.visible
    const fillable = options.includeNonFillable || (!field.disabled && !field.readonly)
    if (visibleEnough && fillable && !isJunkField(field)) {
      fields.push(field)
      fieldEls.push(el)
      counter++
    }
  }

  /** Drop already-collected fields that live inside a newly-found widget root. */
  const dropInside = (widgetRoot: Element): void => {
    for (let i = fieldEls.length - 1; i >= 0; i--) {
      if (widgetRoot.contains(fieldEls[i])) {
        fields.splice(i, 1)
        fieldEls.splice(i, 1)
      }
    }
  }

  const visit = (ctx: FrameContext): void => {
    const elements = ctx.walk.querySelectorAll('*')
    for (const el of Array.from(elements)) {
      if (isSuppressed(el)) continue

      if (isFormControl(el)) {
        push(buildField(el, ctx, `qf-${counter}`), el)
      } else if (isCustomSelectTrigger(el)) {
        const info = detectCustomSelect(el)
        if (info) {
          dropInside(info.widgetRoot)
          push(buildCustomField(info, ctx, `qf-${counter}`), info.widgetRoot)
          suppressed.push(info.widgetRoot)
          continue
        }
      }

      // Descend into an open shadow root if present.
      const shadow = (el as Element & { shadowRoot?: ShadowRoot | null }).shadowRoot
      if (shadow) {
        visit({ frame: ctx.frame, shadow: true, walk: shadow, lookup: shadow })
      }
    }

    // Same-origin iframes only; cross-origin access throws → reported.
    for (const frame of Array.from(ctx.walk.querySelectorAll('iframe'))) {
      const iframe = frame as HTMLIFrameElement
      try {
        const innerDoc = iframe.contentDocument
        if (innerDoc) {
          visit({
            frame: `frame:${frameCounter++}`,
            shadow: ctx.shadow,
            walk: innerDoc,
            lookup: innerDoc,
          })
        } else {
          limitations.push({
            kind: 'crossOriginFrame',
            detail: `Cannot read iframe ${iframe.src || '(no src)'} — likely cross-origin.`,
          })
        }
      } catch {
        limitations.push({
          kind: 'crossOriginFrame',
          detail: `Cross-origin iframe ${iframe.src || '(no src)'} is not accessible.`,
        })
      }
    }
  }

  visit({ frame: 'main', shadow: false, walk: root, lookup: lookupOf(root) })

  return {
    fields,
    limitations,
    structureHash: structureHash(fields),
  }
}

function buildField(el: FormControl, ctx: FrameContext, id: string): DetectedField {
  const inputType = getInputType(el)
  const labelText = getLabelText(el, ctx.lookup)
  const name = el.getAttribute('name') ?? undefined
  const options = getOptions(el)
  const sectionHeading = getSectionHeading(el)
  const fp = fingerprint({
    label: labelText,
    name,
    type: inputType,
    options: options?.map((o) => o.label),
    section: sectionHeading,
  })
  const asInput = el as HTMLInputElement

  return {
    id,
    tagName: el.tagName.toLowerCase(),
    inputType,
    currentValue: getCurrentValue(el),
    required: el.hasAttribute('required') || asInput.required === true,
    disabled: el.hasAttribute('disabled') || asInput.disabled === true,
    readonly: el.hasAttribute('readonly') || asInput.readOnly === true,
    visible: isVisible(el),
    name,
    domId: el.getAttribute('id') ?? undefined,
    classNames: (el.getAttribute('class') ?? '').split(/\s+/).filter(Boolean),
    placeholder: el.getAttribute('placeholder') ?? undefined,
    autocomplete: el.getAttribute('autocomplete') ?? undefined,
    ariaLabel: getAriaLabel(el),
    ariaLabelledByText: getAriaLabelledByText(el, ctx.lookup),
    labelText,
    nearbyText: getNearbyText(el),
    sectionHeading,
    options,
    autocompleteHint: detectAutocomplete(el),
    selectorCandidates: getSelectorCandidates(el),
    domFingerprint: fp.hash,
    frame: ctx.frame,
    shadow: ctx.shadow,
  }
}

/** Build a single DetectedField for a custom (non-native) select widget. */
function buildCustomField(info: CustomSelectInfo, ctx: FrameContext, id: string): DetectedField {
  const { widgetRoot, trigger } = info
  const labelText = getWidgetLabel(widgetRoot, ctx.lookup)
  const name = widgetRoot.getAttribute('name') ?? trigger.getAttribute('name') ?? undefined
  const sectionHeading = getSectionHeading(widgetRoot)
  const options = info.optionLabels.map((label) => ({
    value: label,
    label,
    selected: label === info.selectedLabel,
  }))
  const fp = fingerprint({
    label: labelText,
    name,
    type: 'customSelect',
    options: info.optionLabels,
    section: sectionHeading,
  })

  const customWidget: CustomWidget = {
    kind: 'select',
    triggerSelectorCandidates: getTriggerSelectorCandidates(trigger),
    valueDisplaySelectorCandidates: info.valueDisplay
      ? getSelectorCandidates(info.valueDisplay)
      : [],
    optionItemSelector: info.optionItemSelector,
    optionsOpenOnDemand: true,
  }

  return {
    id,
    tagName: widgetRoot.tagName.toLowerCase(),
    inputType: 'customSelect',
    currentValue: info.selectedLabel,
    required: widgetRoot.getAttribute('aria-required') === 'true',
    disabled: trigger.getAttribute('aria-disabled') === 'true',
    readonly: false,
    visible: isVisible(widgetRoot),
    name,
    domId: widgetRoot.getAttribute('id') ?? undefined,
    classNames: (widgetRoot.getAttribute('class') ?? '').split(/\s+/).filter(Boolean),
    ariaLabel: getAriaLabel(trigger) ?? getAriaLabel(widgetRoot),
    ariaLabelledByText: getAriaLabelledByText(trigger, ctx.lookup),
    labelText,
    sectionHeading,
    options,
    customWidget,
    selectorCandidates: getSelectorCandidates(widgetRoot),
    domFingerprint: fp.hash,
    frame: ctx.frame,
    shadow: ctx.shadow,
  }
}
