// Labeled corpus for the Figma R2 classifier decision gate (see
// docs/FIGMA_PLUGIN_PLAN.md "Decision gate"). Two real tiers — form mockups vs
// dashboard/table mockups — plus decoration/structural noise.
//
// `expectedType` is GROUND TRUTH: the semantic type a designer would want
// auto-filled into that layer, or 'unknown' when no suitable generator exists
// (passwords, usernames, status, decoration, …). It is drawn from the exact
// vocabulary autofill-core can emit. Provenance: representative of real Figma
// Community layer-naming conventions, assembled across 205 candidate names by 8
// category agents and adversarially label-reviewed down to 130 deduped entries —
// NOT scraped from specific community files. Regenerate by re-running the
// figma-r2-corpus workflow if naming conventions shift.

export type Tier = 'forms' | 'dashboard' | 'decoration'

export interface CorpusEntry {
  /** The Figma text-layer name, routed into DetectedField.labelText by the adapter. */
  name: string
  tier: Tier
  /** Ground-truth semantic type (autofill-core vocabulary) or 'unknown'. */
  expectedType: string
  rationale: string
}

// Tier sizes: {"forms":63,"dashboard":46,"decoration":21}
export const FIGMA_R2_CORPUS: readonly CorpusEntry[] = [
  { name: 'Email', tier: 'forms', expectedType: 'email', rationale: 'standard email input label' },
  {
    name: 'Email copy 2',
    tier: 'forms',
    expectedType: 'email',
    rationale: 'duplicated layer from copy-paste, still an email',
  },
  { name: 'Email address', tier: 'forms', expectedType: 'email', rationale: 'verbose email label' },
  {
    name: 'Enter your email',
    tier: 'forms',
    expectedType: 'email',
    rationale: 'placeholder text used as layer name for email',
  },
  {
    name: 'input-email',
    tier: 'forms',
    expectedType: 'email',
    rationale: 'lowercase-dash convention for email input',
  },
  {
    name: 'Work email',
    tier: 'forms',
    expectedType: 'email',
    rationale: 'business email variant on B2B contact form',
  },
  {
    name: 'Newsletter email input',
    tier: 'forms',
    expectedType: 'email',
    rationale: 'newsletter-signup email capture',
  },
  {
    name: 'Password',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'secret credential, no safe generator',
  },
  {
    name: 'Confirm password',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'confirm-password is not autofillable',
  },
  {
    name: 'New Password',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'password-reset field, no generator',
  },
  {
    name: 'Username',
    tier: 'forms',
    expectedType: 'username',
    rationale: 'username/handle field — now covered by the username generator',
  },
  {
    name: 'Full name',
    tier: 'forms',
    expectedType: 'person.fullName',
    rationale: 'full name maps to person.fullName',
  },
  {
    name: 'First name',
    tier: 'forms',
    expectedType: 'person.firstName',
    rationale: 'first name field',
  },
  {
    name: 'Last name',
    tier: 'forms',
    expectedType: 'person.lastName',
    rationale: 'last name field',
  },
  {
    name: 'Name field/Label',
    tier: 'forms',
    expectedType: 'person.fullName',
    rationale: 'component-property Label on a name input',
  },
  {
    name: 'your name',
    tier: 'forms',
    expectedType: 'person.fullName',
    rationale: 'lowercase placeholder-style name field',
  },
  {
    name: 'Cardholder Name',
    tier: 'forms',
    expectedType: 'person.fullName',
    rationale: 'name on the payment card maps to full name',
  },
  {
    name: 'Placeholder',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'generic component-property name, no field context',
  },
  {
    name: 'Value',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'generic component-property name, ambiguous',
  },
  {
    name: 'Input / Label',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'generic input-label property, no field meaning',
  },
  {
    name: 'Label',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'generic component-property name, no fixed semantic',
  },
  {
    name: 'Error message',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'validation feedback text, not a fillable field',
  },
  {
    name: 'input/text 2',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'generic duplicated input layer with no semantic hint',
  },
  {
    name: 'Phone number',
    tier: 'forms',
    expectedType: 'phone',
    rationale: 'phone field maps to phone',
  },
  { name: 'Phone', tier: 'forms', expectedType: 'phone', rationale: 'phone number input' },
  { name: 'Mobile', tier: 'forms', expectedType: 'phone', rationale: 'mobile is a phone number' },
  { name: 'Mobile number', tier: 'forms', expectedType: 'phone', rationale: 'mobile phone field' },
  {
    name: 'DOB',
    tier: 'forms',
    expectedType: 'date',
    rationale: 'date-of-birth abbreviation maps to date',
  },
  { name: 'Birthday', tier: 'forms', expectedType: 'date', rationale: 'birth date field' },
  {
    name: 'Verification code',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'OTP code has no generator',
  },
  {
    name: 'OTP input 1',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'single OTP digit cell, not autofillable',
  },
  {
    name: 'Company',
    tier: 'forms',
    expectedType: 'company',
    rationale: 'company field maps to company',
  },
  {
    name: 'Company name',
    tier: 'forms',
    expectedType: 'company',
    rationale: 'organization field on B2B contact form',
  },
  {
    name: 'Company (optional)',
    tier: 'forms',
    expectedType: 'company',
    rationale: 'optional company name on shipping label',
  },
  { name: 'Organization', tier: 'forms', expectedType: 'company', rationale: 'company/org input' },
  {
    name: 'Remember me',
    tier: 'forms',
    expectedType: 'boolean',
    rationale: 'checkbox toggle maps to boolean',
  },
  {
    name: 'Country',
    tier: 'forms',
    expectedType: 'address.country',
    rationale: 'country selector maps to address.country',
  },
  {
    name: 'country/region',
    tier: 'forms',
    expectedType: 'address.country',
    rationale: 'lowercase combined country field name',
  },
  {
    name: 'ZIP',
    tier: 'forms',
    expectedType: 'address.zip',
    rationale: 'postal code abbreviation maps to address.zip',
  },
  { name: 'ZIP Code', tier: 'forms', expectedType: 'address.zip', rationale: 'postal code field' },
  {
    name: 'Postal code',
    tier: 'forms',
    expectedType: 'address.zip',
    rationale: 'non-US wording for ZIP',
  },
  {
    name: 'Website',
    tier: 'forms',
    expectedType: 'url',
    rationale: 'personal/website URL field maps to url',
  },
  {
    name: 'Bio',
    tier: 'forms',
    expectedType: 'notes',
    rationale: 'free-text biography maps to notes',
  },
  {
    name: 'Message',
    tier: 'forms',
    expectedType: 'notes',
    rationale: 'free-form message textarea maps to notes',
  },
  {
    name: 'comment',
    tier: 'forms',
    expectedType: 'notes',
    rationale: 'lowercase feedback comment body maps to notes',
  },
  {
    name: 'How can we help?',
    tier: 'forms',
    expectedType: 'notes',
    rationale: 'placeholder text used as a layer name for the message body',
  },
  {
    name: 'Address line 1',
    tier: 'forms',
    expectedType: 'address.line1',
    rationale: 'street address first line',
  },
  {
    name: 'Billing Address',
    tier: 'forms',
    expectedType: 'address.line1',
    rationale: 'primary billing street line',
  },
  {
    name: 'Enter your address',
    tier: 'forms',
    expectedType: 'address.line1',
    rationale: 'placeholder text reused as layer name for street line',
  },
  {
    name: 'Address Line 2',
    tier: 'forms',
    expectedType: 'unit',
    rationale: 'second line is typically apartment/suite/unit',
  },
  { name: 'City', tier: 'forms', expectedType: 'address.city', rationale: 'address city part' },
  {
    name: 'State',
    tier: 'forms',
    expectedType: 'address.state',
    rationale: 'address state/province part',
  },
  {
    name: 'State / Province',
    tier: 'forms',
    expectedType: 'address.state',
    rationale: 'state or province field',
  },
  {
    name: 'Apt/Unit',
    tier: 'forms',
    expectedType: 'unit',
    rationale: 'apartment/unit number field',
  },
  {
    name: 'Apt / Unit',
    tier: 'forms',
    expectedType: 'unit',
    rationale: 'apartment or unit number (spacing variant)',
  },
  {
    name: 'Gender',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'enum-ish identity field, forced unknown per rule',
  },
  {
    name: 'Avatar',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'profile image, not a text value',
  },
  {
    name: 'Card Number',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'no card-number generator; not auto-fillable',
  },
  {
    name: 'CVV',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'security code has no safe generator',
  },
  {
    name: 'Expiry Date',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'card expiry is not a real birthday/date value to fill',
  },
  {
    name: 'Subject',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'subject line forced unknown per rule',
  },
  {
    name: 'Subject line copy',
    tier: 'forms',
    expectedType: 'unknown',
    rationale: 'duplicated subject text override, free text, no generator',
  },
  {
    name: 'Topic',
    tier: 'forms',
    expectedType: 'enum',
    rationale: 'support topic dropdown is a categorical selection',
  },
  {
    name: 'Total Revenue',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'revenue KPI is a monetary amount',
  },
  {
    name: 'Revenue',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'bare revenue metric is a currency value',
  },
  {
    name: 'MRR',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'monthly recurring revenue is a money amount',
  },
  {
    name: 'Avg Order Value',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'AOV is a monetary amount',
  },
  {
    name: 'Sales',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'sales figure is a money value',
  },
  {
    name: 'Amount',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'monetary amount column',
  },
  {
    name: 'Amount Due',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'billing amount owed is currency',
  },
  {
    name: 'Price',
    tier: 'dashboard',
    expectedType: 'currency',
    rationale: 'price column maps to currency',
  },
  {
    name: 'Active Users',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'user count is a plain number',
  },
  {
    name: 'Daily Active Users',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'DAU is a count metric',
  },
  {
    name: 'Total Orders',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'order count is a number',
  },
  {
    name: 'Value 2',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'duplicated KPI value slot, numeric',
  },
  {
    name: 'Qty',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'quantity abbreviation is a count',
  },
  {
    name: 'Quantity',
    tier: 'dashboard',
    expectedType: 'number',
    rationale: 'quantity/count column is a number',
  },
  {
    name: 'Conversion Rate',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'percentage rate has no dedicated generator',
  },
  {
    name: 'Conversion',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'conversion metric/percentage has no suitable type',
  },
  {
    name: 'Trend %',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'percent-change delta has no generator',
  },
  {
    name: 'Growth',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'growth percentage metric has no generator',
  },
  {
    name: 'Churn Rate',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'churn percentage has no suitable type',
  },
  {
    name: 'Metric Label',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'descriptive caption text, not a fillable datum',
  },
  {
    name: 'KPI Title',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'widget title text, not user data',
  },
  {
    name: 'Date Range',
    tier: 'dashboard',
    expectedType: 'date',
    rationale: 'date-range selector resolves to a date',
  },
  {
    name: 'X Axis Label',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'axis caption is decorative chart text',
  },
  {
    name: 'Y Axis Label',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'value-axis caption is chart decoration',
  },
  {
    name: 'axis-label',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'generic axis text has no semantic fill',
  },
  {
    name: 'Legend',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'chart legend label is decoration',
  },
  {
    name: 'Name',
    tier: 'dashboard',
    expectedType: 'person.fullName',
    rationale: 'user table name column maps to full name',
  },
  {
    name: 'Assignee',
    tier: 'dashboard',
    expectedType: 'person.fullName',
    rationale: "assignee cell shows the person's full name",
  },
  {
    name: 'Assignee Name',
    tier: 'dashboard',
    expectedType: 'person.fullName',
    rationale: 'explicit full-name label for the assigned user',
  },
  {
    name: 'Owner',
    tier: 'dashboard',
    expectedType: 'person.fullName',
    rationale: 'task owner rendered as a person name',
  },
  {
    name: 'Reporter',
    tier: 'dashboard',
    expectedType: 'person.fullName',
    rationale: "issue reporter is a person's name",
  },
  {
    name: 'Role',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'role/permission enum forced unknown per rule',
  },
  {
    name: 'Status',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'status badge enum forced unknown per rule',
  },
  {
    name: 'status_2',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'duplicated status layer, still no generator',
  },
  {
    name: 'Priority',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'priority enum forced unknown per rule',
  },
  {
    name: 'Tags',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'free-form tags forced unknown per rule',
  },
  {
    name: 'Progress',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'progress bar/percentage forced unknown per rule',
  },
  {
    name: 'Created',
    tier: 'dashboard',
    expectedType: 'date',
    rationale: 'created-at timestamp column',
  },
  {
    name: 'Last Login',
    tier: 'dashboard',
    expectedType: 'date',
    rationale: 'last-login datetime column',
  },
  {
    name: 'Due Date',
    tier: 'dashboard',
    expectedType: 'date',
    rationale: 'deadline column is a date',
  },
  {
    name: 'Start Date',
    tier: 'dashboard',
    expectedType: 'date',
    rationale: 'task start is a date',
  },
  { name: 'Date', tier: 'dashboard', expectedType: 'date', rationale: 'generic date column' },
  {
    name: 'Plan',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'subscription plan tier is an enum, no generator',
  },
  {
    name: 'Workspace Name',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'arbitrary workspace label, no semantic type fits',
  },
  {
    name: 'Project Name',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'free-form project title, no generator',
  },
  {
    name: 'Cell Text 2',
    tier: 'dashboard',
    expectedType: 'unknown',
    rationale: 'duplicated generic cell layer, no semantic meaning',
  },
  {
    name: 'Frame 12',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'auto-generated frame name, no semantic content',
  },
  {
    name: 'Rectangle 47',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'default shape name, purely structural',
  },
  {
    name: 'Group 3',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'auto-generated grouping, carries no field meaning',
  },
  {
    name: 'Ellipse',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'shape primitive, decorative',
  },
  {
    name: 'Vector',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'default vector layer name',
  },
  {
    name: 'Text',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'default text-layer name, meaningless for fill',
  },
  {
    name: 'Heading',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'typographic role, not a form field',
  },
  {
    name: 'Subheading',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'typographic role label',
  },
  {
    name: 'Body',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'body-text style name, decorative',
  },
  {
    name: 'CTA',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'call-to-action button label, no fill data',
  },
  {
    name: 'Button',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'component name, not an input',
  },
  {
    name: 'Icon',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'decorative graphic slot',
  },
  {
    name: 'Badge',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'status badge decoration',
  },
  {
    name: 'Card',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'container component, structural',
  },
  {
    name: 'Row',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'layout row, no semantics',
  },
  {
    name: 'Cell',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'table cell container, field-agnostic',
  },
  {
    name: 'Title',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'section title role, not a form value',
  },
  {
    name: 'Caption',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'caption text style, decorative',
  },
  {
    name: 'text copy 2',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'duplicated default layer, lowercase + trailing number',
  },
  {
    name: 'Frame 238574674',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'raw auto-generated frame id',
  },
  {
    name: 'Rectangle 47 copy',
    tier: 'decoration',
    expectedType: 'unknown',
    rationale: 'duplicated shape, messy real-world artifact',
  },
]
